### PR TITLE
Implementing automatic update

### PR DESCRIPTION
**Pull request by giacomocerquone**
As of issue #15 I'm starting to implement this feature.
Now due to the difficulty I'm having to understand some pieces of the code, I'd like to have some advices on how to implement the settings to be able to turn on/off the "automatic updates" and I think we should add also a "check update" item in the help menu

### CODE REVIEW

**Comment by KurtisLiggett** [comment]
Very nice! Clever thinking.
Only change I would make is use $winVersion instead of $options[0][1]
It should be the same value, but $winVersion is hardcoded and not dependent on the .ini file

**Comment by KurtisLiggett** [comment]
Regarding adding as a new setting, here is the long explaination.
I am working on redoing the whole $options methodology to hopefully make it easier to work with in the future.


First, we need to add an element to the $options array in globals.au3
Also need to add a global variable for the settings checkbox $ck_autoUpdate
```AutoIt
Global $settingsChild, $ck_mintoTray, $ck_startinTray, $ck_saveAdapter, $ck_autoUpdate

Global $options[11][2]
$options[0][0] = "Version"
$options[1][0] = "MinToTray"
$options[2][0] = "StartupMode"
$options[3][0] = "Language"
$options[4][0] = "StartupAdapter"
$options[5][0] = "Theme"
$options[6][0] = "SaveAdapterToProfile"
$options[7][0] = "AdapterBlacklist"
$options[8][0] = "PositionX"
$options[8][1] = ""
$options[9][0] = "PositionY"
$options[9][1] = ""
$options[10][0] = "AutoUpdate"
$options[10][1] = ""
```


Then add the checkbox to the settings window in gui.au3
```AutoIt
Func _Settings()
	...
	GUICtrlSetState($ck_saveAdapter, _StrToState($options[6][1]))
	
	$ck_autoUpdate = GUICtrlCreateCheckbox( "Enable automatic updates.", 10*$dScale, 70*$dScale, 230*$dScale, 20*$dScale)
	GUICtrlSetBkColor(-1, 0xFFFFFF)
	GUICtrlSetState($ck_autoUpdate, _StrToState($options[10][1]))
	...
EndFunc
```


Then add the new option to the save function in functions.au3
```AutoIt
Func _saveOptions()
	$options[2][1] = _StateToStr($ck_startinTray)
	$options[1][1] = _StateToStr($ck_mintoTray)
	$options[6][1] = _StateToStr($ck_saveAdapter)
	$options[10][1] = _StateToStr($ck_autoUpdate)
	IniWriteSection("profiles.ini", "options", $options, 0)
	_onExitSettings()
EndFunc
```


The next section is the _arrange functions in functions.au3
```AutoIt
Func _arrange
	...
	$newfile &= $options[10][0] & "=" & $options[10][1] & @CRLF
```


As a general note, I would like to see a custom window similar to the settings or about popups that gives the prompt to update or cancel, but it also has a checkbox to enable/disable the automatic updates form that popup.

**Comment by KurtisLiggett** [comment]
Let's take this a step further to save the new version, restart, and delete the old.
Here is an example without much error-checking.

```AutoIt
Func _checksSICUpdate()
...
  $newFilename = "Simple.IP.Config."&$info[0]&".exe"
  If ($options[0][1] <> $info[0]) Then
    If MsgBox(1, "Simple-IP-Config Update available", "A new version of Simple-IP-Config has been made publicly available. Press ok to download it.") = 1 Then
      ;ShellExecute($info[1])
	  $res = InetGet ( $info[1], $newFilename)
		if $res > 0 Then
			_DoUpdate($newFilename)
		EndIf
    EndIf
  Else
	if FileExists('simple_ip_config_updater.cmd') Then
		FileDelete('simple_ip_config_updater.cmd')  ;delete updater
	EndIf
  EndIf
...
EndFunc

Func _DoUpdate($newFilename)
	$fileStr = '@echo off' & @CRLF & _
				'taskkill /pid ' & WinGetProcess($hgui) & @CRLF & _	;kill running instance
				'del /Q "' & @ScriptFullPath & '"' & @CRLF & _ ;delete old version
				'start "" "' & $newFilename & '"' ;start new version
	$filename = 'simple_ip_config_updater.cmd'
	$file = FileOpen($filename, 2) ;open/overwrite
	FileWrite($file, $fileStr)
	FileClose($file)

	$iPID = Run(@ComSpec & " /k " & $filename, "", @SW_HIDE, $STDIN_CHILD+$STDERR_MERGED)
EndFunc
```

**Comment by giacomocerquone** [comment]
Ok, I'll implement this ASAP.
Two question:

1. Do you want to include a json library? (i'd say to leave it like this, without importing anything else)
2. I saw that github limits your request to 60 per hours and this could potentially lead to problems! Do we wanna check update periodically? (everyday/everyweek/everymonth)
3. ok for the update, I thought it'd be better to let the user download and install the new version whenever he wants, but the decision is yours 😄

**Comment by KurtisLiggett** [comment]
1. Let's leave it like it is for now.
2. I wonder if we could download a version.ini file from the repo instead?
3. Let's not do the self-deleting thing for now. Maybe in the future we might want to add it, or present the option to the user possibly.

**Comment by giacomocerquone** [comment]
2. yes I didn't think about it but we don't have a version.ini yet (upload to the repo the profiles.ini is semantically wrong). We just have to get the raw file from the repo. The [readme](https://raw.githubusercontent.com/KurtisLiggett/Simple-IP-Config/master/README.md) for example
3. What self-deleting thing? Do you mean the auto delete of simple-ip-config-updater.cmd?

**Comment by KurtisLiggett** [comment]
2. I was just thinking we make a file called version with the contents
```
2.8.1
```
Then do something like this from the helpfile,
```AutoIt
    ; Read the file without downloading to a folder. The option of 'get the file from the local cache' has been selected.
    Local $dData = InetRead("http://www.autoitscript.com/autoit3/files/beta/update.dat")

    ; The number of bytes read is returned using the @extended macro.
    Local $iBytesRead = @extended

    ; Convert the ANSI compatible binary string back into a string.
    Local $sData = BinaryToString($dData)
```

3. Yes just keep the download like you have it where the user selects the download location and can proceed however they want.

**Comment by giacomocerquone** [comment]
3. ok
2. this is a bit of a mess... I suppose you took that piece from internet. The comment says that use the cache but actually they didn't put the 0 flag and we MUST NOT use the cache.
I'd use always something like I wrote using a get request.
Anyway I think we can't do this because I forgot that the API are important also to grab the download link of the last release...

**Comment by KurtisLiggett** [comment]
> this is a bit of a mess... I suppose you took that piece from internet. The comment says that use the cache but actually they didn't put the 0 flag and we MUST NOT use the cache.

That code section was from the help file and was just meant to be an example of a more straightforward way to get the remote file.
It works exactly as advertised because 0 is the default flag if no flag is specified. Using a flag of 1 forces a reload and would work for our purposes.

In any case, I'm good with the method you used, so I'll go ahead and merge.

**Comment by KurtisLiggett** [comment]
I'm not yet familiar with GitHub practices completely. If I want to add the custom window myself, can (or should) I commit to your fork branch before merging or is it better to merge your contributions then create a new branch to make my changes?

**Comment by giacomocerquone** [comment]
It is your preference but it's adviced to add it to the new branch when the commit you want to add is relative to the reason the branch has been created

**Pull request merged**
